# mypy - project requires strict typechecking because this is a C++ port
[tool.mypy]
python_version = "3.11"
strict = true

# black
[tool.black]
line-length = 72
target-version = ['py311']

# isort
[tool.isort]
profile = "black"
line_length = 72
skip = ["env/"]
